version: '3'
services:
  # openapi-server:
  #   image: golang:1.14-alpine
  #   container_name: golang-example-app-openapi-server
  #   volumes:
  #     - ../../:/workspace
  #   working_dir: /workspace
  #   tty: true
  #   hostname: grpc-server
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - golang_example_app
  #   command: >
  #     go run cmd/openapi-server/main.go
  grpc-main-server:
    image: golang:1.14-alpine
    container_name: golang-example-app-grpc-main-server
    volumes:
      - ../../:/workspace
    working_dir: /workspace
    tty: true
    hostname: grpc-main-server
    ports:
      - 4002:4002
    networks:
      - golang_example_app
    environment:
      LOGPATH: /workspace/server/grpc-main-server/log/grpc-main-server.log
    command: >
      go run server/grpc-main-server/main.go
  grpc-service1-server:
    image: golang:1.14-alpine
    container_name: golang-example-app-grpc-service1-server
    volumes:
      - ../../:/workspace
    working_dir: /workspace
    tty: true
    hostname: grpc-service1-server
    ports:
      - 4003:4003
    networks:
      - golang_example_app
    environment:
      LOGPATH: /workspace/server/grpc-gateway-server/log/grpc-service1-server.log
    command: >
      go run server/grpc-service1-server/main.go
  grpc-service2-server:
    image: golang:1.14-alpine
    container_name: golang-example-app-grpc-service2-server
    volumes:
      - ../../:/workspace
    working_dir: /workspace
    tty: true
    hostname: grpc-service2-server
    ports:
      - 4004:4004
    networks:
      - golang_example_app
    environment:
      LOGPATH: /workspace/server/grpc-gateway-server/log/grpc-service2-server.log
    command: >
      go run server/grpc-service2-server/main.go
  grpc-gateway-server:
    image: golang:1.14-alpine
    container_name: golang-example-app-grpc-gateway-server
    volumes:
      - ../../:/workspace
    working_dir: /workspace
    tty: true
    hostname: gateway-server
    ports:
      - 4001:4001
    networks:
      - golang_example_app
    environment:
      LOGPATH: /workspace/server/grpc-gateway-server/log/grpc-gateway-server.log
    command: >
      go run server/grpc-gateway-server/main.go
  # 以下古い
  # grpc-server:
  #   image: golang:1.14-alpine
  #   container_name: golang-example-app-grpc-server
  #   volumes:
  #     - ../../:/workspace
  #   working_dir: /workspace
  #   tty: true
  #   hostname: grpc-server
  #   ports:
  #     - 3002:3002
  #   networks:
  #     - golang_example_app
  #   command: >
  #     go run cmd/grpc-server/main.go
  # grpc-sub-server:
  #   image: golang:1.14-alpine
  #   container_name: golang-example-app-grpc-sub-server
  #   volumes:
  #     - ../../:/workspace
  #   working_dir: /workspace
  #   tty: true
  #   hostname: grpc-sub-server
  #   ports:
  #     - 3012:3012
  #   networks:
  #     - golang_example_app
  #   command: >
  #     go run cmd/grpc-sub-server/main.go
  # grpc-gateway-server:
  #   image: golang:1.14-alpine
  #   container_name: golang-example-app-grpc-gateway-server
  #   volumes:
  #     - ../../:/workspace
  #   working_dir: /workspace
  #   tty: true
  #   hostname: gateway-server
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - golang_example_app
  #   command: >
  #     go run cmd/grpc-gateway-server/main.go
networks:
  golang_example_app:
    external: true
volumes:
  dotgit:
    driver: 'local'