version: '3'
services:
  openapi-server:
    image: golang:1.14-alpine
    container_name: golang-example-app-openapi-server
    volumes:
      - ../../:/workspace
    working_dir: /workspace
    tty: true
    hostname: grpc-server
    ports:
      - 3000:3000
    networks:
      - golang_example_app
    command: >
      go run cmd/openapi-server/main.go
  grpc-server:
    image: golang:1.14-alpine
    container_name: golang-example-app-grpc-server
    volumes:
      - ../../:/workspace
    working_dir: /workspace
    tty: true
    hostname: grpc-server
    ports:
      - 3002:3002
    networks:
      - golang_example_app
    command: >
      go run cmd/grpc-server/main.go
  # grpc-sub-server:
  #   image: golang:1.14-alpine
  #   container_name: golang-example-app-grpc-server
  #   volumes:
  #     - ../../:/workspace
  #   working_dir: /workspace
  #   tty: true
  #   hostname: grpc-server
  #   ports:
  #     - 3002:3002
  #   networks:
  #     - golang_example_app
  #   command: >
  #     go run grpc-web/server/grpc/main.go
  grpc-gateway-server:
    image: golang:1.14-alpine
    container_name: golang-example-app-grpc-gateway-server
    volumes:
      - ../../:/workspace
    working_dir: /workspace
    tty: true
    hostname: gateway-server
    ports:
      - 3001:3001
    networks:
      - golang_example_app
    command: >
      go run cmd/grpc-gateway-server/main.go
networks:
  golang_example_app:
    external: true