version: '3'
services:
  # openapi-server:
  #   image: golang:1.14-alpine
  #   container_name: golang-example-app-openapi-server
  #   volumes:
  #     - ../../:/workspace
  #   working_dir: /workspace
  #   tty: true
  #   hostname: grpc-server
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - golang_example_app
  #   command: >
  #     go run cmd/openapi-server/main.go
  grpc-main-server:
    image: golang:1.14-alpine
    container_name: golang-example-app-grpc-main-server
    volumes:
      - ../../:/workspace
    working_dir: /workspace
    tty: true
    hostname: grpc-main-server
    ports:
      - 4002:4002
    networks:
      - golang_example_app
    environment:
      LOGPATH: /workspace/grpc-main-server/logs/grpc-main-server.log
    command: >
      go run grpc-main-server/main.go
  grpc-service1-server:
    image: golang:1.14-alpine
    container_name: golang-example-app-grpc-service1-server
    volumes:
      - ../../:/workspace
    working_dir: /workspace
    tty: true
    hostname: grpc-service1-server
    ports:
      - 4003:4003
    networks:
      - golang_example_app
    environment:
      LOGPATH: /workspace/grpc-service1-server/logs/grpc-service1-server.log
    command: >
      go run grpc-service1-server/main.go
  grpc-service2-server:
    image: golang:1.14-alpine
    container_name: golang-example-app-grpc-service2-server
    volumes:
      - ../../:/workspace
    working_dir: /workspace
    tty: true
    hostname: grpc-service2-server
    ports:
      - 4004:4004
    networks:
      - golang_example_app
    environment:
      LOGPATH: /workspace/grpc-service2-server/logs/grpc-service2-server.log
    command: >
      go run grpc-service2-server/main.go
  grpc-gateway-server:
    image: golang:1.14-alpine
    container_name: golang-example-app-grpc-gateway-server
    volumes:
      - ../../:/workspace
    working_dir: /workspace
    tty: true
    hostname: gateway-server
    ports:
      - 4001:4001
    networks:
      - golang_example_app
    environment:
      LOGPATH: /workspace/grpc-gateway-server/logs/grpc-gateway-server.log
    command: >
      go run grpc-gateway-server/main.go
networks:
  golang_example_app:
    external: true
