/*
 * golang-example-app
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetUserResponse struct {
	Name string `json:"name,omitempty"`

	Age int32 `json:"age,omitempty"`
}
