version: '3'
services:
  godb:
    build: ./
    image: golang-example-app/mariadb
    command: mysqld --lower_case_table_names=1 --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    container_name: godb
    hostname: godb
    ports:
      - "13340:3306"
    environment:
      - MYSQL_DATABASE=godb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - godb
networks:
  godb:
    external: true