/*
 * golang-example-app
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"
)

// A ExampleApiController binds http requests to an api service and writes the service results to the http response
type ExampleApiController struct {
	service ExampleApiServicer
}

// NewExampleApiController creates a default api controller
func NewExampleApiController(s ExampleApiServicer) Router {
	return &ExampleApiController{service: s}
}

// Routes returns all of the api route for the ExampleApiController
func (c *ExampleApiController) Routes() Routes {
	return Routes{
		{
			"GetAge",
			strings.ToUpper("Get"),
			"/echo",
			c.GetAge,
		},
	}
}

// GetAge - age
func (c *ExampleApiController) GetAge(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetAge()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
