/*
 * golang-example-app
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// ExampleApiService is a service that implents the logic for the ExampleApiServicer
// This service should implement the business logic for every endpoint for the ExampleApi API.
// Include any external packages or services that will be required by this service.
type ExampleApiService struct {
}

// NewExampleApiService creates a default api service
func NewExampleApiService() ExampleApiServicer {
	return &ExampleApiService{}
}

// GetUsers - all users
func (s *ExampleApiService) GetUsers() (interface{}, error) {
	// TODO - update GetUsers with the required logic for this service method.
	// Add api_example_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetUsers' not implemented")
}

// PostUser - create user
func (s *ExampleApiService) PostUser(postUserRequest PostUserRequest) (interface{}, error) {
	// TODO - update PostUser with the required logic for this service method.
	// Add api_example_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'PostUser' not implemented")
}
