name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - 1.14.6
    steps:
    - uses: actions/setup-go@v2
      with:
          stable: 'true'
          go-version: ${{ matrix.go }}
    - name: setup
      run: go mod download
    - uses: actions/checkout@v2
    - name: execute golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.30
    - name: execute goimports
      run: goimports -e -d -local github.com ./grpc-*