name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - 1.14.6
    steps:
    - uses: actions/setup-go@v2
      with:
          stable: 'true'
          go-version: ${{ matrix.go }}
    - name: checkout
      uses: actions/checkout@v2
    - name: cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: execute golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.30
    - name: install goimports
      run: go get golang.org/x/tools/cmd/goimports
    - name: execute goimports
      run: goimports -e -d -local github.com ./grpc-*