name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
          stable: 'true'
          go-version: '1.14.6'
    - name: setup
      run: make setup
    - name: Execute lint
      run: make lint
