name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
          stable: 'true'
          go-version: '1.14.6'
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.30
    - name: setup
      run: go mod download
    - name: execute lint
      run: >
        golangci-lint run
        goimports -e -d -local github.com ./grpc-*